const CategoriesObject = [
  {
    id: 1,
    title: "Zonda",
    image: "/img/logosempresas/zonda.png",
    category: "cargadoresyarrancadores",
    link: "",
  },
  {
    id: 2,
    title: "Laser",
    image: "",
    category: "cargadoresyarrancadores",
    link: "",
  },
  {
    id: 3,
    title: "Aleba",
    image: "",
    category: "cargadoresyarrancadores",
    link: "",
  },
  {
    id: 4,
    title: "Rico",
    image: "",
    category: "chaperia",
    link: "",
  },
  {
    id: 5,
    title: "Hidraulicos Rocaru",
    image: "",
    category: "chaperia",
    link: "",
  },
  {
    id: 6,
    title: "Industrial Stark Tools",
    image: "",
    category: "chaperia",
    link: "",
  },
  {
    id: 7,
    title: "Fema",
    image: "",
    category: "compresoresdeaire",
    link: "",
  },
  {
    id: 8,
    title: "Riddle Pro",
    image: "",
    category: "elevadoresdeauto",
    link: "",
  },
  {
    id: 9,
    title: "Riddle Pro",
    image: "",
    category: "extractoresycomprimidos",
    link: "",
  },
  {
    id: 10,
    title: "Industrial Stark Tools",
    image: "",
    category: "extractoresycomprimidos",
    link: "",
  },
  {
    id: 11,
    title: "Raselli",
    image: "",
    category: "gomeria",
    link: "",
  },
  {
    id: 12,
    title: "Slime",
    image: "",
    category: "gomeria",
    link: "",
  },
  {
    id: 13,
    title: "Gamma",
    image: "",
    category: "herramientaselectricas",
    link: "",
  },
  {
    id: 14,
    title: "Lüsatoff",
    image: "",
    category: "herramientaselectricas",
    link: "",
  },
  {
    id: 15,
    title: "Motomel",
    image: "",
    category: "herramientaselectricas",
    link: "",
  },
  {
    id: 16,
    title: "UMI",
    image: "",
    category: "herramientaselectricas",
    link: "",
  },
  {
    id: 17,
    title: "Herramientas Especiales",
    image: "",
    category: "herramientasespeciales",
    link: "",
  },
  {
    id: 18,
    title: "TR Sinfines - Metalúrgica",
    image: "",
    category: "herramientasespeciales",
    link: "",
  },
  {
    id: 19,
    title: "Bremen",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 20,
    title: "Davidson",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 21,
    title: "Eurotech",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 22,
    title: "Lüsatoff",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 23,
    title: "Riddle Pro",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 24,
    title: "N. Rucci",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 25,
    title: "Ruhlmann",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 26,
    title: "Trupper",
    image: "",
    category: "herramientasmanuales",
    link: "",
  },
  {
    id: 27,
    title: "Berta",
    image: "",
    category: "herramientasneumaticas",
    link: "",
  },
  {
    id: 28,
    title: "VTB",
    image: "",
    category: "herramientasneumaticas",
    link: "",
  },
  {
    id: 29,
    title: "Recoil",
    image: "",
    category: "insertos",
    link: "",
  },
  {
    id: 30,
    title: "MB",
    image: "",
    category: "inyeccionelectronica",
    link: "",
  },
  {
    id: 31,
    title: "PDM",
    image: "",
    category: "inyeccionelectronica",
    link: "",
  },
  {
    id: 32,
    title: "Uni-t",
    image: "",
    category: "inyeccionelectronica",
    link: "",
  },
  {
    id: 33,
    title: "Riddle Pro",
    image: "",
    category: "juegosdetubos",
    link: "",
  },
  {
    id: 34,
    title: "Extrapol Herramientas",
    image: "",
    category: "juegosdetubos",
    link: "",
  },
  {
    id: 35,
    title: "Bemar",
    image: "",
    category: "lubricacion",
    link: "",
  },
  {
    id: 36,
    title: "Cherta",
    image: "",
    category: "lubricacion",
    link: "",
  },
  {
    id: 37,
    title: "JIT Lubricación",
    image: "",
    category: "lubricacion",
    link: "",
  },
  {
    id: 38,
    title: "Powersilens",
    image: "",
    category: "lubricacion",
    link: "",
  },
  {
    id: 39,
    title: "Casagrande Hnos. S.R.L.",
    image: "",
    category: "mobiliarioparatalleres",
    link: "",
  },
  {
    id: 40,
    title: "Motormech",
    image: "",
    category: "mobiliarioparatalleres",
    link: "",
  },
  {
    id: 41,
    title: "Palladino Equipamientos",
    image: "",
    category: "mobiliarioparatalleres",
    link: "",
  },
  {
    id: 42,
    title: "Tayg",
    image: "",
    category: "mobiliarioparatalleres",
    link: "",
  },
  {
    id: 43,
    title: "Metalúrgica Sur",
    image: "",
    category: "prensaehidraulicos",
    link: "",
  },
  {
    id: 44,
    title: "Erreve",
    image: "",
    category: "prensaehidraulicos",
    link: "",
  },
  {
    id: 45,
    title: "Hidráulicos Costa",
    image: "",
    category: "prensaehidraulicos",
    link: "",
  },
  {
    id: 46,
    title: "Puesta a Punto",
    image: "",
    category: "puestaapunto",
    link: "",
  },
  {
    id: 47,
    title: "TR Sinfines - Metalúrgica",
    image: "",
    category: "puestaapunto",
    link: "",
  },
  {
    id: 48,
    title: "Elekttro",
    image: "",
    category: "sacabollos",
    link: "",
  },
  {
    id: 49,
    title: "Elekttro",
    image: "",
    category: "soldadoras",
    link: "",
  },
  {
    id: 50,
    title: "Laser",
    image: "",
    category: "soldadoras",
    link: "",
  },

  {
    id: 51,
    title: "Vesubio",
    image: "",
    category: "soldadoras",
    link: "",
  },
];
export default CategoriesObject;

// {
//     id: ,
//     title: ,
//     image: ,
//     category: ,
//     link: ,
// }
