const CategoriesObject = [
  {
    id: 1,
    title: "Zonda",
    image: require("../img/logosempresas/zonda.png"),
    category: "cargadoresyarrancadores",
    link: "https://drive.google.com/file/d/1AtSmdhbSuwImhhPDOm7K8znYr2FG8rus/view",
  },
  {
    id: 2,
    title: "Laser",
    image: require("../img/logosempresas/laser.png"),
    category: "cargadoresyarrancadores",
    link: "https://drive.google.com/file/d/1rt2QcinNNJ7CC6ARVs-97KEVJUsQEGgI/view",
  },
  // {
  //   id: 3,
  //   title: "Aleba",
  //   image: require("../img/logosempresas/aleba.png"),
  //   category: "cargadoresyarrancadores",
  //   link: "",
  // },
  {
    id: 4,
    title: "Rico",
    image: require("../img/logosempresas/rico.jpg"),
    category: "chaperia",
    link: "https://drive.google.com/file/d/1r-_WEhkcpxAKldJPxC0__g68KlEgmFno/view",
  },
  {
    id: 5,
    title: "Hidraulicos Rocaru",
    image: require("../img/logosempresas/rocaru.jpg"),
    category: "chaperia",
    link: "https://drive.google.com/file/d/1mntXZmyAMbpYoZurG_mzkWSqfPmuH3fj/view",
  },
  {
    id: 6,
    title: "Industrial Stark Tools",
    image: require("../img/logosempresas/stark.jpg"),
    category: "chaperia",
    link: "https://drive.google.com/file/d/1CBjVr2VzW93IcMvdPPmyJ89K5E882Z7M/view",
  },
  // {
  //   id: 7,
  //   title: "Fema",
  //   image: require("../img/logosempresas/fema.jpg"),
  //   category: "compresoresdeaire",
  //   link: "",
  // },
  {
    id: 8,
    title: "Riddle Pro",
    image: require("../img/logosempresas/riddlepro.png"),
    category: "elevadoresdeauto",
    link: "https://drive.google.com/file/d/1CBjVr2VzW93IcMvdPPmyJ89K5E882Z7M/view",
  },
  {
    id: 9,
    title: "Riddle Pro",
    image: require("../img/logosempresas/riddlepro.png"),
    category: "extractoresycomprimidos",
    link: "https://drive.google.com/file/d/1CBjVr2VzW93IcMvdPPmyJ89K5E882Z7M/view",
  },
  {
    id: 10,
    title: "Industrial Stark Tools",
    image: require("../img/logosempresas/stark.jpg"),
    category: "extractoresycomprimidos",
    link: "https://drive.google.com/file/d/1CBjVr2VzW93IcMvdPPmyJ89K5E882Z7M/view",
  },
  {
    id: 11,
    title: "Raselli",
    image: require("../img/logosempresas/raselli.png"),
    category: "gomeria",
    link: "https://drive.google.com/file/d/16uUAOg8RUyIfBud5smSo0NPUvnZvhYu4/view",
  },
  // {
  //   id: 12,
  //   title: "Slime",
  //   image: require("../img/logosempresas/slime.png"),
  //   category: "gomeria",
  //   link: "",
  // },
  {
    id: 13,
    title: "Gamma",
    image: require("../img/logosempresas/gamma.png"),
    category: "herramientaselectricas",
    link: "https://drive.google.com/file/d/1l2rRuW7gdEx3TmxgWtdCJ0hKDBqk2k20/view",
  },
  // {
  //   id: 14,
  //   title: "Lüsatoff",
  //   image: require("../img/logosempresas/lusatoff.png"),
  //   category: "herramientaselectricas",
  //   link: "",
  // },
  // {
  //   id: 15,
  //   title: "Motomel",
  //   image: require("../img/logosempresas/motomel.png"),
  //   category: "herramientaselectricas",
  //   link: "",
  // },
  {
    id: 16,
    title: "UMI",
    image: require("../img/logosempresas/umi.png"),
    category: "herramientaselectricas",
    link: "https://drive.google.com/file/d/1xylh1UrshyFlS-Oqna4LTQuZ54dUolOe/view",
  },
  {
    id: 17,
    title: "Herramientas Especiales",
    image: require("../img/logosempresas/herramientasespeciales.jpg"),
    category: "herramientasespeciales",
    link: "https://drive.google.com/file/d/1yG_YmHHSFEelijz0nujvfWADS7H78mCi/view",
  },
  // {
  //   id: 18,
  //   title: "TR Sinfines - Metalúrgica",
  //   image: require("../img/logosempresas/tr.jpg"),
  //   category: "herramientasespeciales",
  //   link: "",
  // },
  // {
  //   id: 19,
  //   title: "Bremen",
  //   image: require("../img/logosempresas/bremen.png"),
  //   category: "herramientasmanuales",
  //   link: "",
  // },
  {
    id: 20,
    title: "Davidson",
    image: require("../img/logosempresas/davidson.png"),
    category: "herramientasmanuales",
    link: "https://drive.google.com/file/d/1wJg_-8gLD2v58G0b42eZXmbe1VDl6YSb/view",
  },
  {
    id: 21,
    title: "Eurotech",
    image: require("../img/logosempresas/eurotech.png"),
    category: "herramientasmanuales",
    link: "https://drive.google.com/file/d/1eoZ7_5c3W4hw5AV2SCBBjS27iEV3ZjrP/view",
  },
  // {
  //   id: 22,
  //   title: "Lüsatoff",
  //   image: require("../img/logosempresas/lusatoff.png"),
  //   category: "herramientasmanuales",
  //   link: "",
  // },
  {
    id: 23,
    title: "Riddle Pro",
    image: require("../img/logosempresas/riddlepro.png"),
    category: "herramientasmanuales",
    link: "https://drive.google.com/file/d/1CBjVr2VzW93IcMvdPPmyJ89K5E882Z7M/view",
  },
  {
    id: 24,
    title: "N. Rucci",
    image: require("../img/logosempresas/nrucci.jpg"),
    category: "herramientasmanuales",
    link: "https://drive.google.com/file/d/1ah8LSBtMKaMppbeJxfQxkxElSJ1g2el4/view",
  },
  {
    id: 25,
    title: "Ruhlmann",
    image: require("../img/logosempresas/ruhlmann.png"),
    category: "herramientasmanuales",
    link: "https://drive.google.com/file/d/1N9kt71sAC5cqXpSSEhRtyXgaVzEg98Ze/view",
  },
  // {
  //   id: 26,
  //   title: "Trupper",
  //   image: require("../img/logosempresas/truper.png"),
  //   category: "herramientasmanuales",
  //   link: "",
  // },
  {
    id: 27,
    title: "Berta",
    image: require("../img/logosempresas/berta.png"),
    category: "herramientasneumaticas",
    link: "https://drive.google.com/file/d/1VWK7CKwTQTCGiDvs68GRgOnOehqqBeNs/view",
  },
  {
    id: 28,
    title: "VTB",
    image: require("../img/logosempresas/vtb.png"),
    category: "herramientasneumaticas",
    link: "https://drive.google.com/file/d/18GYj4-YodnATRMAnYsMaU90-SO4QeJxC/view",
  },
  {
    id: 29,
    title: "Recoil",
    image: require("../img/logosempresas/recoil.png"),
    category: "insertos",
    link: "https://drive.google.com/file/d/1idwCRAgQpo1ppVLibtkHwagujh75jtX3/view",
  },
  {
    id: 30,
    title: "MB",
    image: require("../img/logosempresas/mb.png"),
    category: "inyeccionelectronica",
    link: "https://drive.google.com/file/d/1kmLIMapjp1XO39DOAlQGOzgB3ZD6zboQ/view",
  },
  // {
  //   id: 31,
  //   title: "PDM",
  //   image: require("../img/logosempresas/pdm.jpg"),
  //   category: "inyeccionelectronica",
  //   link: "",
  // },
  {
    id: 32,
    title: "Uni-t",
    image: require("../img/logosempresas/uni-t.jpg"),
    category: "inyeccionelectronica",
    link: "https://drive.google.com/file/d/1dRaKkWNDF7SrzerDmSoi090FSHBOnsU_/view",
  },
  {
    id: 33,
    title: "Riddle Pro",
    image: require("../img/logosempresas/riddlepro.png"),
    category: "juegosdetubos",
    link: "https://drive.google.com/file/d/1CBjVr2VzW93IcMvdPPmyJ89K5E882Z7M/view",
  },
  // {
  //   id: 34,
  //   title: "Extrapol Herramientas",
  //   image: require("../img/logosempresas/extrapol.png"),
  //   category: "juegosdetubos",
  //   link: "",
  // },
  {
    id: 35,
    title: "Bemar",
    image: require("../img/logosempresas/bemar.png"),
    category: "lubricacion",
    link: "https://drive.google.com/file/d/1n5Kh5DtwTsaGzeqiLtnudlnHUbEgWjI5/view",
  },
  {
    id: 36,
    title: "Cherta",
    image: require("../img/logosempresas/cherta.png"),
    category: "lubricacion",
    link: "https://drive.google.com/file/d/1po8iNv0BzuXJ76V5E9m8TCF1zwfNiudG/view",
  },
  // {
  //   id: 37,
  //   title: "JIT Lubricación",
  //   image: require("../img/logosempresas/jit.png"),
  //   category: "lubricacion",
  //   link: "",
  // },
  // {
  //   id: 38,
  //   title: "Powersilens",
  //   image: require("../img/logosempresas/powersilens.png"),
  //   category: "lubricacion",
  //   link: "",
  // },
  {
    id: 39,
    title: "Casagrande Hnos. S.R.L.",
    image: require("../img/logosempresas/casagrandehnos.png"),
    category: "mobiliarioparatalleres",
    link: "https://drive.google.com/file/d/1CvHpVEFIVAKgL6oID85FomQxfjLP313f/view",
  },
  {
    id: 40,
    title: "Motormech",
    image: require("../img/logosempresas/motormech.png"),
    category: "mobiliarioparatalleres",
    link: "https://drive.google.com/file/d/18LbggdMuPG9Olk7PTDGqWPhhfUT_asgn/view",
  },
  {
    id: 41,
    title: "Palladino Equipamientos",
    image: require("../img/logosempresas/palladino.jpg"),
    category: "mobiliarioparatalleres",
    link: "https://drive.google.com/file/d/1yp7qqKsknjQ2cmSnVPnX3_3dwsf7ydq0/view",
  },
  {
    id: 42,
    title: "Tayg",
    image: require("../img/logosempresas/tayg.png"),
    category: "mobiliarioparatalleres",
    link: "https://drive.google.com/file/d/1n408zY09-3nkh7lrzSMOiRDf2mIMsr9R/view",
  },
  // {
  //   id: 43,
  //   title: "Metalúrgica Sur",
  //   image: require("../img/logosempresas/metalurgicasur.png"),
  //   category: "prensaehidraulicos",
  //   link: "",
  // },
  {
    id: 44,
    title: "Erreve",
    image: require("../img/logosempresas/erreve.jpg"),
    category: "prensaehidraulicos",
    link: "https://drive.google.com/file/d/1n408zY09-3nkh7lrzSMOiRDf2mIMsr9R/view",
  },
  // {
  //   id: 45,
  //   title: "Hidráulicos Costa",
  //   image: require("../img/logosempresas/hidraulicoscosta.jpg"),
  //   category: "prensaehidraulicos",
  //   link: "",
  // },
  // {
  //   id: 46,
  //   title: "Puesta a Punto",
  //   image: require("../img/logosempresas/puestaapunto.png"),
  //   category: "puestaapunto",
  //   link: "",
  // },
  // {
  //   id: 47,
  //   title: "TR Sinfines - Metalúrgica",
  //   image: require("../img/logosempresas/tr.jpg"),
  //   category: "puestaapunto",
  //   link: "",
  // },
  {
    id: 48,
    title: "Elekttro",
    image: require("../img/logosempresas/elekttro.png"),
    category: "sacabollos",
    link: "https://drive.google.com/file/d/1n408zY09-3nkh7lrzSMOiRDf2mIMsr9R/view",
  },
  {
    id: 49,
    title: "Elekttro",
    image: require("../img/logosempresas/elekttro.png"),
    category: "soldadoras",
    link: "https://drive.google.com/file/d/1n408zY09-3nkh7lrzSMOiRDf2mIMsr9R/view",
  },
  {
    id: 50,
    title: "Laser",
    image: require("../img/logosempresas/laser.png"),
    category: "soldadoras",
    link: "https://drive.google.com/file/d/1rt2QcinNNJ7CC6ARVs-97KEVJUsQEGgI/view",
  },

  {
    id: 51,
    title: "Vesubio",
    image: require("../img/logosempresas/vesubio.jpg"),
    category: "soldadoras",
    link: "https://drive.google.com/file/d/1-3ZlmTW9OhKfnu7TTS-R4Y9mK7ZqCEZL/view",
  },
];
export default CategoriesObject;

// {
//     id: ,
//     title: ,
//     image: ,
//     category: ,
//     link: ,
// }
